import { createElement } from '@lwc/engine-dom';
import AutomobileSales30_90 from 'c/automobileSales30_90';

describe('c-automobile-sales30-90', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-automobile-sales30-90', {
            is: AutomobileSales30_90
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});